csp2/discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

csp2/discussion/todolist/urls.py
from django.urls import path
from . import views

# Syntax
# path(route, view, name)

app_name = 'todolist'

urlpatterns = [
	path('', views.index, name='index'),
	# /todolist/<todoitem_id>
	# /todolist/1
	# The <int:todoitem_id> allows for creating a dynamic link where the todoitem_id is provided
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	path('event/<int:todoevent_id>/', views.todoevent, name='viewtodoevent'),
	# /todolist/register
	path('register', views.register, name='register'),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('update_profile', views.update_profile, name='update_profile'),
	path('add_task', views.add_task, name="add_task"),
	path('add_event', views.add_event, name="add_event"),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete',views.delete_task, name='delete_task')
]

csp2/discussion/todolist/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class ToDoEvent(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	event_date = models.DateTimeField('event date')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

csp2/discussion/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class updateProfileForm(forms.Form):
	firstName = forms.CharField(label='firstName', max_length=40)
	lastName = forms.CharField(label='lastName', max_length=40)
	password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label='Event Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	firstName = forms.CharField(label='firstName', max_length=40)
	lastName = forms.CharField(label='lastName', max_length=40)
	email = forms.CharField(label='email', max_length=50)
	password = forms.CharField(label='Password', max_length=20)
	confirmPassword = forms.CharField(label='confirmPassword', max_length=20)

csp2/discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.forms.utils import timezone


from .models import ToDoItem, ToDoEvent
from .forms import LoginForm, AddTaskForm, AddEventForm, UpdateTaskForm, RegisterForm

def index(request):
	# todoitem_list = ToDoItem.objects.all()	
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	todoevent_list = ToDoEvent.objects.filter(user_id=request.user.id)
	template = loader.get_template("todolist/index.html")
	context = {
	'todoitem_list': todoitem_list,
	'user': request.user,
	'todoevent_list': todoevent_list
	}
	return render(request, "todolist/index.html", context )

	# return HttpResponse(template.render(context, request))
	# output = ', '.join([todoitem.task_name for todoitem in todoitem_list])
	# return HttpResponse(output)
	# return HttpResponse("Hello from the views.py file")

def todoitem(request, todoitem_id):
	# todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

	# response = "You are viewing the details of %s"
	# return HttpResponse(response % todoitem_id)

def todoevent(request, todoevent_id):
	# todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
	todoevent = get_object_or_404(ToDoEvent, pk=todoevent_id)
	return render(request, "todolist/todoevent.html", model_to_dict(todoevent))

def register(request):
	users = User.objects.all()

	is_user_registered = False
	is_same_password = True
	context = {
	"is_user_registered": is_user_registered
	}

	if request.method == 'POST':

		form = RegisterForm(request.POST)

		if form.is_valid() == False:

			form = RegisterForm()

		else:

			username = form.cleaned_data['username']
			firstName = form.cleaned_data['firstName']
			lastName = form.cleaned_data['lastName']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			confirmPassword = form.cleaned_data['confirmPassword']	

			if password is not confirmPassword:
				is_same_password = False
				

			for indiv_user in users:
				if indiv_user.username == username:
					is_user_registered = True
					break


			if is_user_registered == False:
				user = User()
				user.username = username
				user.first_name = firstName
				user.last_name = lastName
				user.email = email
				# user.password = "john1234"
				# The set_password method is used to ensure that the password is hashed
				user.set_password(password)
				user.is_staff = False
				user.is_active = True
				user.save()
				context = {
				"first_name": user.first_name,
				"last_name": user.last_name
				}	
	

	return render(request, "todolist/register.html", context)



def update_profile(request):
	is_user_authenticated = False
	context = {
		'user': request.user,
	}

	if request.method == 'POST':

		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:

			form = UpdateTaskForm()

		else:

			request.user.first_name = form.cleaned_data['firstName']
			request.user.last_name = form.cleaned_data['lastName']



	# user = authenticate(username="johndoe")
	# print(user)

	# if user is not None:
	# 	user = User.objects.get(username="johndoe")
	# 	user.set_password("johndoe123")
	# 	user.save()

	# 	is_user_authenticated = True

	context = {
		"is_user_authenticated": is_user_authenticated,
		"firstName": request.user.first_name,
		"lastName": request.user.last_name,
		"password": request.user.password
	}

	return render(request, "todolist/update_profile.html", context)	



def login_view(request):
	context = {}

	if request.method == 'POST':

		form = LoginForm(request.POST)

		if form.is_valid() == False:

			form = LoginForm()

		else:

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password
			}

			if user is not None:

				login(request, user)
				return redirect("todolist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "todolist/login.html", context)
	# username="johndoe"
	# password="johndoe1"
	# user = authenticate(username = username, password = password)
	# print(user)


	# if user is not None:
	# 	login(request, user)
	# 	return redirect("todolist:index")
	# else:
	# 	return render(request, "todolist/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):

	context = {}

	if request.method == 'POST':

		form = AddTaskForm(request.POST)

		if form.is_valid() == False:

			form = AddTaskForm()

		else:

			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']


			duplicates = ToDoItem.objects.filter(task_name=task_name)

			if not duplicates:

				ToDoItem.objects.create(task_name=task_name, description=description,
					date_created=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def add_event(request):

	context = {}

	if request.method == 'POST':

		form = AddEventForm(request.POST)

		if form.is_valid() == False:

			form = AddTaskForm()

		else:

			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']


			duplicates = ToDoEvent.objects.filter(event_name=event_name)

			if not duplicates:

				ToDoEvent.objects.create(event_name=event_name, description=description,
					event_date=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/add_event.html", context)


def update_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}

	if request.method == 'POST':

		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:

			form = UpdateTaskForm()

		else:

			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:

				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/update_task.html", context)

def delete_task (request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")

csp2/discussion/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add An Event</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate event found</p>
				{% endif %}
				<form action="{% url 'todolist:add_event' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="event_name">Event Name: </label>
					<input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="50" required>
				</div>

				<div class="mb-3">
					<label for="description">Description:</label>
					<textarea class="form-control" name="description" 
					value="{{ description }}" required></textarea>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Add Event">
				</div>

				</form>
			</div>
		</div>
	</div>
{% endblock %}

csp2/discussion/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add A Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}
				<form action="{% url 'todolist:add_task' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="task_name">Task Name: </label>
					<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
				</div>

				<div class="mb-3">
					<label for="description">Description:</label>
					<textarea class="form-control" name="description" 
					value="{{ description }}" required></textarea>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Add Task">
				</div>

				</form>
			</div>
		</div>
	</div>
{% endblock %}

csp2/discussion/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{%block title %}Home{% endblock %}

{%block content %}
{% if todoitem_list and user.is_anonymous == False %}
	<h1 class="text-center my-3">Welcome {{user.first_name}} 
	{{user.last_name}}!</h1>
	<div class="container">
		<div class="row">
			<h3 class="text-center mb-3">My Tasks</h3>
			<ul class="list-group col-lg-2 offset-lg-5 text-center"> 
			{% for todoitem in todoitem_list %}
				<li class="list-group-item"><a href="{% url 'todolist:viewtodoitem' todoitem.id %}"
					class="text-decoration-none">{{todoitem.task_name}}</a></li>
			{% endfor %}
			</ul>
		</div>
	</div>
	
{% elif user.is_anonymous == True %}
	<h1 class="text-center my-3">You are not authorized to access this page.</h1>
	<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
{% else %}
	<h3 class="text-center mb-3">My Tasks</h3>
	<p class="text-center">No tasks have been created.</p>

{% endif %}

{% if todoevent_list and user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<h3 class="text-center mb-3 mt-4">My Events</h3>
			<ul class="list-group col-lg-2 offset-lg-5 text-center"> 
			{% for todoevent in todoevent_list %}
				<li class="list-group-item"><a href="{% url 'todolist:viewtodoevent' todoevent.id %}"
					class="text-decoration-none">{{todoevent.event_name}}</a></li>
			{% endfor %}
			</ul>
		</div>
	</div>
	
{% elif user.is_anonymous == True%}
	<p></p>
{% else %}
	<h3 class="text-center mb-3 mt-4">My Events</h3>
	<p class="text-center">No events have been created.</p>

{% endif %}
{%endblock %}

csp2/discussion/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{%block title %}Login{% endblock %}

{%block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your
				username and password</p>
			{% endif %}
			<form action="{% url 'todolist:login' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username:</label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="password">New Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Login">
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}


<!-- {% if is_user_authenticated == False %}
	<h1>Something went Wrong</h1>
	<p>Please contact your administrator or reset your password</p>
	<a href="{% url 'todolist:index' %}">Back to index page</a>
{% endif %} -->

csp2/discussion/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{%block title %}Register{% endblock %}

{%block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Register</h1>
			{% if is_user_registered == False %}
			<h3>Duplicate User Found!</h3>
			<p>A duplicate user has been found, user creation unsuccessful</p>
			{% else %}
			<h3>User Successfully Created!</h3>
			<p>The account for {{first_name}} {{last_name}} has been successfully created.</p>
			{% endif %}

			<form action="{% url 'todolist:register' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username:</label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="firstName">First Name:</label>
					<input class="form-control" id="firstName" type="text" name="firstName" value="{{ firstName }}" maxlength="40" required>
				</div>

				<div class="mb-3">
					<label for="lastName">Last Name:</label>
					<input class="form-control" id="lastName" type="text" name="lastName" value="{{ lastName }}" maxlength="40" required>
				</div>

				<div class="mb-3">
					<label for="email">Email:</label>
					<input class="form-control" id="email" type="email" name="email" value="{{ email }}" maxlength="50" required>
				</div>

				<div class="mb-3">
					<label for="password">Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
					{% if is_same_password == False %}
					<p class="text-danger">Password does not match</p>
					{% endif %}
				</div>

				<div class="mb-3">
					<label for="confirmPassword">Confirm Password:</label>
					<input class="form-control" id="confirmPassword" type="password" name="confirmPassword" value="{{ confirmPassword }}" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Register">
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}

csp2/discussion/todolist/templates/todolist/todoevent.html
{% extends 'base.html' %}

{%  block title %}{{event_name}}{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{event_name}}</h1>
	<h3>Description</h3>
	<p>{{description}}</p>
	<h3>Status</h3>
	<p>{{status}}</p>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">
		Back To Events</a>
	</button>

</div>
{% endblock %}

csp2/discussion/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{%  block title %}{{task_name}}{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{task_name}}</h1>
	<h3>Description</h3>
	<p>{{description}}</p>
	<h3>Status</h3>
	<p>{{status}}</p>

	<button class="btn btn-primary mx-1 text-decoration-none">
		<a href="{% url 'todolist:update_task' id%}" class="text-light text-decoration-none">
		Edit Task</a>
	</button>

	<button class="btn btn-danger mx-1 text-decoration-none">
		<a href="{% url 'todolist:delete_task' id%}" class="text-light text-decoration-none">
		Delete Task</a>
	</button>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">
		Back To Tasks</a>
	</button>

</div>
{% endblock %}

csp2/discussion/todolist/templates/todolist/update_profile.html
{% extends 'base.html' %}

{%block title %} Update Profile {% endblock %}

{%block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<!-- {% if is_user_authenticated == False %}
				<h1>Invalid User Credentials</h1>
				<p>Check if the username and password is correct.</p>

			{% else %}
				<h1>User Password Successfully Updated!</h1>
				<p>The Password has been successfully updated!</p>

			{% endif %} -->
			
			<h1 class="text-center my-3">Update Profile</h1>

			<form action="{% url 'todolist:update_profile' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="firstName">First Name:</label>
					<input class="form-control" id="firstName" type="text" name="firstName" value="{{ firstName }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="lastName">Last Name:</label>
					<input class="form-control" id="lastName" type="text" name="lastName" value="{{ lastName }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="password">Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Update Profile">
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}

csp2/discussion/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">Task not found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="task_name">Task Name:</label>
						<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="description">Description:</label>
						<textarea class="form-control" name="description" required>{{ description }}
						</textarea>
					</div>

					<div class="mb-3">
						<label for="status">Status:</label>
						<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Update Task">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.
		</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}